import os
from dotenv import load_dotenv

load_dotenv()

class Settings:
    HOST: str = os.getenv("HOST", "127.0.0.1")
    PORT: int = int(os.getenv("PORT", 8000))

    # VLM
    VLM_BACKEND_TYPE: str = os.getenv(
        "VLM_BACKEND_TYPE",
        "mock"
    )

    OLLAMA_URL: str = os.getenv(
        "OLLAMA_URL",
        "http://localhost:11434"
    )

    OLLAMA_MODEL: str = os.getenv(
        "OLLAMA_MODEL",
        "qwen2-vl:7b"
    )

    # ============================================================
    # Google OAuth 2.0 / OpenID Connect
    # ============================================================

    # Web Application OAuth client ID
    GOOGLE_CLIENT_ID: str = os.getenv(
        "GOOGLE_CLIENT_ID",
        "390639826881-0obrs7o2o8smin06jnbtvu46ci975b5r.apps.googleusercontent.com"
    )

    # IMPORTANT:
    # Keep the OAuth client secret ONLY on the server.
    # Never put this value inside the Chrome extension.
    GOOGLE_CLIENT_SECRET: str = os.getenv(
        "GOOGLE_CLIENT_SECRET",
        ""
    )

    GOOGLE_TOKEN_ENDPOINT: str = os.getenv(
        "GOOGLE_TOKEN_ENDPOINT",
        "https://oauth2.googleapis.com/token"
    )

    GOOGLE_USERINFO_ENDPOINT: str = os.getenv(
        "GOOGLE_USERINFO_ENDPOINT",
        "https://openidconnect.googleapis.com/v1/userinfo"
    )

    # Must match the redirect URI registered in Google Cloud
    # and the URI generated by chrome.identity.getRedirectURL().
    GOOGLE_REDIRECT_URI: str = os.getenv(
        "GOOGLE_REDIRECT_URI",
        "https://bbnkaebaegjkgdfhfnlnlkfhgpolfmhk.chromiumapp.org/"
    )

    GOOGLE_REQUIRED_SCOPES: set[str] = {
        "openid",
        "email",
        "profile",
    }

settings = Settings()
